homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 26.7
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customizations 
  customize: !include customize.yaml

automation: !include automation.yaml
script: !include script.yaml
group: !include groups.yaml
scene: !include scenes.yaml

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  ssl_certificate: !secret cert
  ssl_key: !secret key

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

#wink:
#  access_token: !secret wink_key

alarm_control_panel:
  platform: simplisafe
  username: !secret simplisafe_username
  password: !secret simplisafe_password 

zwave:
  usb_path: /dev/zwavestick
  polling_interval: 30000
  customize:
    light.living_room_level_3_0:
      polling_intensity: 1
      refresh_value: true
      delay: 3
    light.kitchen_counter_level_4_0:
      polling_intensity: 1
      refresh_value: true
      delay: 3

emulated_hue:

ecobee:
  api_key: !secret ecobee_key

media_player:
  - platform: roku

mqtt:
  broker: 192.168.1.2
  port: 1883
  client_id: home-assistant-1
  keepalive: 60

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
    consider_home: 0:10
    track_new_devices: False
  - platform: bluetooth_tracker
    track_new_devices: False
  - platform: owntracks
    max_gps_accuracy: 200

zone: !include zones.yaml

notify:
  - name: pushbullet 
    platform: pushbullet
    api_key: !secret pushbullet_key

shell_command:
  arm_blink: /custom_scripts/blinkarm.sh
  disarm_blink: /custom_scripts/blinkdisarm.sh


